[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Headers for proper MIME types
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects - static assets first, then SPA fallback
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = false

[[redirects]]
  from = "/*.mjs"
  to = "/:splat.mjs"
  status = 200
  force = false

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200
  force = false

[[redirects]]
  from = "/*.json"
  to = "/:splat.json"
  status = 200
  force = false

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = false

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  force = false

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false